// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBynT6-1hcL8HPsWjpd1uJo3x_xAIWDcLQ',
    appId: '1:881511245003:web:1d5d1944b5ad17db09a74e',
    messagingSenderId: '881511245003',
    projectId: 'teja-techcamp',
    authDomain: 'teja-techcamp.firebaseapp.com',
    storageBucket: 'teja-techcamp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3uZ2R6eQCK_Db7FlXEt8Pxnp_YzF6XQo',
    appId: '1:881511245003:android:a152eb7bbd8a114309a74e',
    messagingSenderId: '881511245003',
    projectId: 'teja-techcamp',
    storageBucket: 'teja-techcamp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrneEGS1dwMEyvRPp-1crEyjdU_-2jWe0',
    appId: '1:881511245003:ios:10b9790c38796b9609a74e',
    messagingSenderId: '881511245003',
    projectId: 'teja-techcamp',
    storageBucket: 'teja-techcamp.appspot.com',
    iosClientId: '881511245003-hv4oeo7ucgbnbo4vs0046mlgscg0bafb.apps.googleusercontent.com',
    iosBundleId: 'com.example.temanJalan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrneEGS1dwMEyvRPp-1crEyjdU_-2jWe0',
    appId: '1:881511245003:ios:10b9790c38796b9609a74e',
    messagingSenderId: '881511245003',
    projectId: 'teja-techcamp',
    storageBucket: 'teja-techcamp.appspot.com',
    iosClientId: '881511245003-hv4oeo7ucgbnbo4vs0046mlgscg0bafb.apps.googleusercontent.com',
    iosBundleId: 'com.example.temanJalan',
  );
}
